# Generated by Django 3.1.5 on 2021-01-31 14:46

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mediators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', phone_field.models.PhoneField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_amount', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('orders', models.CharField(blank=True, max_length=50)),
                ('delivery_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('link', models.URLField(max_length=252)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('star_rating', models.IntegerField()),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.orderdetail')),
            ],
        ),
    ]
