# Generated by Django 3.1.5 on 2021-01-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20210131_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='orders',
            field=models.CharField(max_length=50),
        ),
    ]
