# Generated by Django 3.1.5 on 2021-01-31 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_auto_20210131_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='orders',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_amount',
            field=models.IntegerField(),
        ),
    ]
